name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Validate app
        run: python -m py_compile app/app.py


  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

          echo "IMAGE_NAME=ghcr.io/$OWNER/$REPO:latest" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME ./app

      - name: Push Docker image
        run: docker push $IMAGE_NAME


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Convert repository name to lowercase
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

          echo "IMAGE_NAME=ghcr.io/$OWNER/$REPO:latest" >> $GITHUB_ENV

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

            docker pull $IMAGE_NAME

            docker stop hello-world || true
            docker rm hello-world || true

            docker run -d \
              --name hello-world \
              --restart always \
              -p 5000:5000 \
              $IMAGE_NAME